name: pull-request
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up node 
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm install
      - name: Build packages 
        run: npm run build --workspaces
      - name: Run tests 
        run: npm run test --workspaces